
export const SIGNUP_USER = "SIGNUP_USER"
export const SIGNIN_USER = "SIGNIN_USER"
export const SIGNOUT_USER = "SIGNOUT_USER"

export const SET_ALERT = "SET_ALERT"
export const RESET_ALERT = "RESET_ALERT"

export const SIGNEDIN_USER = "SIGNEDIN_USER"
export const SIGNEDOUT_USER = "SIGNEDOUT_USER"

export const FORGOT_USER= "FORGOT_USER"

export const GOOGLESIGNIN_USER = "GOOGLESIGNIN_USER"

export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DEREMENT_COUNTER = "DEREMENT_COUNTER"
export const PRODUCT_GETDATA = "PRODUCT_GETDATA"

export const LOADING_PRODUCT = "LOADING_PRODUCT"
export const ERROR_PRODUCT = "ERROR_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"

export const GETDATA_CATEGORY = "GETDATA_CATEGORY"
export const ADD_CATEGORY = "ADD_CATEGORY"
export const ERROR_CATEGORY = "ERROR_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"

export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_CART = "DELETE_CART"
export const CART_INCREMENT = "CART_INCREMENT"
export const CART_DECREMENT = "CART_DECREMENT"
export const CART_EMPTY = "CART_EMPTY"

export const GET_ORDER_DATA = "GET_ORDER_DATA"
export const ADD_ORDER_DATA = "GET_ORDER_DATA"